include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/**/*.gr.dart"
    - "lib/**/*.g.dart"
    - "lib/generated/**"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    - prefer_final_locals
    - prefer_final_fields
    - require_trailing_commas
    - prefer_single_quotes
    - omit_local_variable_types