name: tiberium_crm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  auto_route: ^8.1.3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/