name: tiberium_crm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  auto_route: ^8.1.3
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/